list: $/martinimultimedia/events/models/tag/columns.yaml
modelClass: MartiniMultimedia\Events\Models\Tag
title: Tags
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/events/tags/update/:id'
